# Generated by Django 2.2 on 2019-05-08 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_auto_20190508_1216'),
        ('account', '0002_auto_20190507_2049'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categorypreference',
            table='account_category_preferences',
        ),
        migrations.AlterModelTable(
            name='profilepreference',
            table='account_profile_preferences',
        ),
        migrations.AlterModelTable(
            name='themepreference',
            table='account_theme_preferences',
        ),
        migrations.CreateModel(
            name='ArticleBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_datetime', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_set', related_query_name='bookmark', to='publication.Article')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
            options={
                'db_table': 'account_article_bookmarks',
                'unique_together': {('profile', 'article')},
            },
        ),
    ]
