# Generated by Django 2.2 on 2019-05-08 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190508_1216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleBookmark',
        ),
    ]
