# Generated by Django 2.2 on 2019-05-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_articlebookmark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profilepreference',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='profilepreference',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profilepreference',
            name='subject_profile',
        ),
        migrations.AlterUniqueTogether(
            name='themepreference',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='themepreference',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='themepreference',
            name='theme',
        ),
        migrations.DeleteModel(
            name='CategoryPreference',
        ),
        migrations.DeleteModel(
            name='ProfilePreference',
        ),
        migrations.DeleteModel(
            name='ThemePreference',
        ),
    ]
