# Generated by Django 2.2 on 2019-05-08 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypreference',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_set', related_query_name='preference', to='tags.Category'),
        ),
        migrations.AlterField(
            model_name='themepreference',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_set', related_query_name='preference', to='tags.Theme'),
        ),
    ]
