# Generated by Django 2.2 on 2019-05-08 22:12

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedArticle',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('publications.article',),
        ),
    ]
