# Generated by Django 2.2 on 2019-05-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follows',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='themepreference',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='themepreference',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='themepreference',
            name='theme',
        ),
        migrations.DeleteModel(
            name='CategoryPreference',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ThemePreference',
        ),
    ]
