# Generated by Django 2.2 on 2019-05-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_auto_20190508_1216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='commentvote',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentvote',
            name='user',
        ),
        migrations.DeleteModel(
            name='ArticleVote',
        ),
        migrations.DeleteModel(
            name='CommentVote',
        ),
    ]
