# Generated by Django 2.2 on 2019-05-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20190508_2125'),
        ('publication', '0005_auto_20190508_2057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='tags.Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='themes',
            field=models.ManyToManyField(to='tags.Theme'),
        ),
    ]
