# Generated by Django 2.2 on 2019-05-11 19:39

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_rating', models.FloatField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='accounts.Profile')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_set', related_query_name='recommendation', to='tags.Theme')),
            ],
            options={
                'db_table': 'recommendation_themes',
                'unique_together': {('profile', 'theme')},
            },
        ),
    ]
